name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j
      - name: Create test data
        run: |
          mkdir -p test_data
          echo "алгоритм поиска" > test_data/notes1.txt
          echo "данные алгоритм" > test_data/notes2.txt 
      - name: Run binary
        run: ./build/stlfind test_data "алгоритм"
